import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.health': 'Salud',
    'nav.dental': 'Odontología',
    'nav.medicine': 'Medicina',
    'nav.tours': 'Tour de Experiencia',
    'nav.customTrips': 'Experiencia Logística',
    'nav.logistics': 'Tour Diseñadores',
    'nav.pricing': 'Tarifas',
    'nav.contact': 'Contacto',
    'nav.cta': 'Solicitar Valoración',
    
    // Hero
    'hero.slide1.title': 'Excelencia Médica con Corazón Local',
    'hero.slide1.subtitle': 'Tu aliado ideal en planificación médica VIP en Medellín',
    'hero.slide1.cta': 'Iniciar Proceso',
    'hero.slide2.title': 'Odontología Integral Especializada',
    'hero.slide2.subtitle': 'Contamos con los mejores especialistas en estética dental, rehabilitación oral, implantes y mucho más.',
    'hero.slide2.cta': 'Ver más',
    'hero.slide3.title': 'Colombia en su Máxima Expresión',
    'hero.slide3.subtitle': 'Logística bilingüe y experiencias exclusivas mientras te recuperas',
    'hero.slide3.cta': 'Explorar Experiencias',
    
    // About Section
    'about.label': 'Sobre Nosotros',
    'about.title': 'No solo prestamos un servicio: acompañamos vidas',
    'about.description': 'Patry Ally nació de la pasión por transformar el turismo médico en una experiencia humana y cálida. Somos el puente entre pacientes internacionales y los mejores especialistas de Colombia, garantizando tranquilidad, seguridad y resultados excepcionales.',
    'about.stat1': 'Pacientes',
    'about.stat2': 'Especialistas',
    'about.stat3': 'Satisfacción',
    'about.human.title': 'Acompañamiento Humano',
    'about.human.desc': 'Estamos contigo en cada paso, desde tu llegada hasta tu regreso. No eres un número, eres parte de nuestra familia.',
    'about.network.title': 'Red de Especialistas',
    'about.network.desc': 'Acceso a cirujanos y especialistas certificados con años de experiencia.',
    'about.quality.title': 'Calidad Garantizada',
    'about.quality.desc': 'Alianzas con clínicas de alto nivel y seguimiento post-operatorio integral.',

    // Specialties
    'specialties.label': 'Especialidades',
    'specialties.title': 'Portafolio de Turismo Médico',
    'specialties.subtitle': 'Accede a los mejores especialistas de Colombia con tecnología de vanguardia',
    'specialties.custom': '¿No encuentras lo que buscas? ¡Te lo conseguimos!',
    'specialties.plastic': 'Cirugía Plástica',
    'specialties.plastic.desc': 'Procedimientos estéticos y reconstructivos con cirujanos de renombre internacional.',
    'specialties.dental': 'Odontología',
    'specialties.dental.desc': 'Diseño de sonrisa, implantes y rehabilitación oral con tecnología de última generación.',
    'specialties.cardio': 'Cardiología',
    'specialties.cardio.desc': 'Diagnóstico y tratamiento integral de enfermedades cardiovasculares.',
    'specialties.gastro': 'Gastroenterología',
    'specialties.gastro.desc': 'Evaluación completa del sistema digestivo con equipos de alta tecnología.',
    'specialties.checkups': 'Chequeos Ejecutivos',
    'specialties.checkups.desc': 'Evaluación integral de salud para ejecutivos y profesionales.',
    'specialties.sports': 'Medicina Deportiva',
    'specialties.sports.desc': 'Tratamiento y prevención de lesiones deportivas con especialistas certificados.',
    'specialties.derma': 'Dermatología',
    'specialties.derma.desc': 'Tratamientos de piel, rejuvenecimiento facial y procedimientos estéticos dermatológicos.',
    'specialties.ortho': 'Ortopedia',
    'specialties.ortho.desc': 'Diagnóstico y tratamiento de lesiones y enfermedades del sistema musculoesquelético.',
    'specialties.ophtha': 'Oftalmología',
    'specialties.ophtha.desc': 'Cirugía láser, cataratas e intervenciones oculares con tecnología avanzada.',
    'specialties.cta': 'Conocer más',

    // Process Timeline
    'process.label': 'Tu Proceso',
    'process.title': 'Acompañamiento 360°',
    'process.subtitle': 'Te guiamos en cada paso del camino hacia tu transformación',
    'process.step1.title': 'Asesoría Virtual',
    'process.step1.desc': 'Evaluamos tu caso y diseñamos un plan personalizado con los mejores especialistas.',
    'process.step2.title': 'Llegada VIP',
    'process.step2.desc': 'Recogida en aeropuerto, transporte bilingüe y alojamiento de primera clase.',
    'process.step3.title': 'Procedimiento Médico',
    'process.step3.desc': 'Atención médica de excelencia con seguimiento constante de nuestro equipo.',
    'process.step4.title': 'Recuperación & Bienestar',
    'process.step4.desc': 'Cuidado post-operatorio, spa, y experiencias únicas mientras te recuperas.',
    
    // Essence Section
    'essence.title': 'El Acompañamiento es nuestra Esencia',
    'essence.subtitle': 'Somos tu aliado en cada paso del proceso médico, garantizando tranquilidad y seguridad desde el primer contacto hasta tu regreso a casa.',
    'essence.cta': 'Conoce nuestro método',
    
    // Pillars Section
    'pillars.title': 'Pilares de Excelencia',
    'pillars.medical.title': 'Excelencia Médica',
    'pillars.medical.desc': 'Especialistas de alto nivel con certificaciones internacionales y años de experiencia.',
    'pillars.logistics.title': 'Logística VIP',
    'pillars.logistics.desc': 'Transporte bilingüe puerta a puerta y gestión total de tu estadía.',
    'pillars.experiences.title': 'Experiencias Únicas',
    'pillars.experiences.desc': 'Tours exclusivos diseñados para que descubras lo mejor de Medellín.',
    
    // CTA Banner
    'cta.banner.title': '¿Listo para tu nueva versión?',
    'cta.banner.subtitle': 'Habla con un asesor VIP',
    'cta.banner.button': 'WhatsApp Directo',
    
    // Difference Section
    'difference.title': 'La Diferencia Patry Ally',
    'difference.subtitle': 'Transformamos el turismo médico en una experiencia humana y personalizada',
    'difference.human.title': 'Acompañamiento Humano',
    'difference.human.desc': 'Estamos contigo en cada paso, desde tu llegada hasta tu regreso. No eres un número, eres parte de nuestra familia.',
    'difference.security.title': 'Seguridad y Confianza',
    'difference.security.desc': 'Gestión integral de seguros y alianzas con clínicas de alto nivel certificadas internacionalmente.',
    'difference.logistics.title': 'Logística Puerta a Puerta',
    'difference.logistics.desc': 'Puntualidad garantizada en aeropuertos, citas médicas y traslados. Tu tiempo es invaluable.',
    
    // Services Grid
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Experiencias diseñadas para tu bienestar',
    'services.medicine': 'Medicina Especializada',
    'services.medicine.desc': 'Cirugía plástica, odontología y más',
    'services.tours': 'Experiencias Premium',
    'services.tours.desc': 'Tours exclusivos en Medellín',
    'services.logistics': 'Logística VIP',
    'services.logistics.desc': 'Transporte y hospedaje de lujo',
    
    // Medicine Page (Legacy)
    'medicine.hero.title': 'Salud & Odontología',
    'medicine.hero.subtitle': 'Accede a los mejores especialistas de Colombia con atención personalizada',
    'medicine.specialties.title': 'Nuestras Especialidades',
    'medicine.plastic': 'Cirugía Plástica',
    'medicine.plastic.desc': 'Procedimientos estéticos con cirujanos certificados de renombre internacional',
    'medicine.dental': 'Diseño de Sonrisa',
    'medicine.dental.desc': 'Odontología estética de vanguardia con tecnología de última generación',
    'medicine.gastro': 'Gastroenterología',
    'medicine.gastro.desc': 'Diagnóstico y tratamiento integral del sistema digestivo',
    'medicine.cardio': 'Chequeos Ejecutivos',
    'medicine.cardio.desc': 'Evaluación completa de salud con equipos de alta tecnología',
    'medicine.implants': 'Implantes Dentales',
    'medicine.implants.desc': 'Soluciones permanentes para tu sonrisa perfecta',
    'medicine.tech.title': 'Tecnología y Diagnóstico',
    'medicine.tech.subtitle': 'Equipamiento de última generación para tu tranquilidad',
    'medicine.ultrasound': 'Ecografías',
    'medicine.labs': 'Laboratorios',
    'medicine.sports': 'Medicina Deportiva',
    'medicine.cta': 'Solicitar valoración',

    // Health Page (New Authority Structure)
    'health.hero.label': 'Turismo Médico de Élite',
    'health.hero.title': 'Excelencia Médica en Medellín',
    'health.hero.subtitle': 'Accede a especialistas de clase mundial, tecnología de vanguardia y un acompañamiento integral que garantiza tu tranquilidad en cada paso del proceso.',
    'health.hero.cta': 'Solicitar Valoración Virtual',

    'health.banner.text': 'Nuestro valor no es solo la medicina, es el acompañamiento bilingüe en cada cita y la gestión integral de tus trámites.',

    'health.directory.label': 'Directorio de Alto Nivel',
    'health.directory.title': 'Nuestro Cuadro Médico',
    'health.directory.subtitle': 'Especialistas certificados internacionalmente con años de experiencia en pacientes internacionales',

    'health.plastic.title': 'Cirugía Plástica y Reconstructiva',
    'health.plastic.desc': 'Cirujanos de renombre internacional especializados en procedimientos estéticos y reconstructivos con las técnicas más avanzadas.',
    'health.plastic.proc1': 'Liposucción HD y Lipotransferencia',
    'health.plastic.proc2': 'Mamoplastia de Aumento y Reducción',
    'health.plastic.proc3': 'Rinoplastia y Cirugía Facial',
    'health.plastic.proc4': 'Abdominoplastia y Contorno Corporal',

    'health.gastro.title': 'Gastroenterología',
    'health.gastro.desc': 'Diagnóstico y tratamiento integral del sistema digestivo con tecnología endoscópica de última generación.',
    'health.gastro.proc1': 'Balón Gástrico Intragástrico',
    'health.gastro.proc2': 'Endoscopia Digestiva',
    'health.gastro.proc3': 'Colonoscopia de Alta Definición',

    'health.cardio.title': 'Cardiología',
    'health.cardio.desc': 'Evaluación cardiovascular completa con equipos de alta tecnología y especialistas certificados.',
    'health.cardio.proc1': 'Ecocardiograma Doppler',
    'health.cardio.proc2': 'Prueba de Esfuerzo',
    'health.cardio.proc3': 'Monitoreo Holter 24h',

    'health.neuro.title': 'Neurofisiología',
    'health.neuro.desc': 'Diagnóstico neurológico avanzado para evaluación del sistema nervioso central y periférico.',
    'health.neuro.proc1': 'Electroencefalograma (EEG)',
    'health.neuro.proc2': 'Electromiografía',
    'health.neuro.proc3': 'Potenciales Evocados',

    'health.ortho.title': 'Ortopedia',
    'health.ortho.desc': 'Tratamiento de lesiones musculoesqueléticas con cirujanos especializados en medicina deportiva.',
    'health.ortho.proc1': 'Artroscopia de Rodilla',
    'health.ortho.proc2': 'Reemplazo de Articulaciones',
    'health.ortho.proc3': 'Cirugía de Columna Mínimamente Invasiva',

    'health.dental.title': 'Odontología de Alto Nivel',
    'health.dental.desc': 'Diseño de sonrisa integral con tecnología CAD/CAM y especialistas en estética dental.',
    'health.dental.proc1': 'Diseño de Sonrisa Digital',
    'health.dental.proc2': 'Implantes Dentales Premium',
    'health.dental.proc3': 'Carillas de Porcelana',
    'health.dental.proc4': 'Rehabilitación Oral Completa',

    'health.cta.consult': 'Consultar Especialista',

    'health.alliances.label': 'Red Institucional',
    'health.alliances.title': 'Alianzas Estratégicas',
    'health.alliances.subtitle': 'Respaldados por las instituciones más prestigiosas del turismo médico en Colombia',
    'health.alliances.partners': 'Trabajamos con las mejores clínicas y laboratorios de Medellín',

    'health.alliance.cluster': 'Cluster Medellín Health City',
    'health.alliance.cluster.desc': 'Miembros activos del ecosistema de turismo de salud más importante de Latinoamérica.',
    'health.alliance.clinics': 'Clínicas Certificadas',
    'health.alliance.clinics.desc': 'Red de clínicas con certificaciones JCI y acreditaciones internacionales.',

    'health.exec.label': 'Diagnóstico Premium',
    'health.exec.title': 'Chequeo Ejecutivo',
    'health.exec.description': 'Evaluación integral de salud diseñada para ejecutivos y profesionales internacionales. Diagnóstico completo en tiempo récord con los mejores especialistas.',
    'health.exec.cta': 'Agendar Chequeo Ejecutivo',

    'health.exec.echo': 'Ecografías',
    'health.exec.echo.desc': 'Ecografía abdominal, pélvica, tiroides y vascular con equipos de última generación.',
    'health.exec.ecg': 'Electrocardiograma',
    'health.exec.ecg.desc': 'Evaluación de la actividad eléctrica cardíaca para detección temprana.',
    'health.exec.holter': 'Holter 24 Horas',
    'health.exec.holter.desc': 'Monitoreo continuo del ritmo cardíaco durante actividades diarias.',
    'health.exec.lab': 'Laboratorio de Patología',
    'health.exec.lab.desc': 'Análisis clínicos completos con resultados en 24-48 horas.',
    'health.exec.molecular': 'Diagnóstico Molecular',
    'health.exec.molecular.desc': 'Pruebas genéticas y marcadores tumorales de alta precisión.',
    'health.exec.sports': 'Medicina Deportiva BIUMAN',
    'health.exec.sports.desc': 'Evaluación funcional y prevención de lesiones para atletas.',

    'health.exec.biuman.title': 'Medicina Deportiva BIUMAN',
    'health.exec.biuman.desc': 'Programa especializado en evaluación biomecánica, prevención de lesiones y optimización del rendimiento deportivo con tecnología de análisis de movimiento.',

    'health.routes.title': 'Rutas de Diagnóstico Rápido',
    'health.routes.desc': 'Diseñamos rutas de diagnóstico eficientes para ejecutivos internacionales que necesitan resultados completos en tiempo limitado.',
    'health.routes.item1': 'Chequeo cardiovascular completo en 4 horas',
    'health.routes.item2': 'Perfil oncológico preventivo en 24 horas',
    'health.routes.item3': 'Evaluación integral de salud en 48 horas',
    'health.routes.time': 'Resultados completos',
    'health.allies.title': 'Aliados',


    
    // Tours Page
    'tours.hero.title': 'Experiencias & Tours',
    'tours.hero.subtitle': 'Descubre Colombia con experiencias exclusivas diseñadas para ti',
    'tours.orchids': 'Orquídeas Alma del Bosque',
    'tours.orchids.desc': 'Sumérgete en el mundo de las orquídeas en un santuario natural único',
    'tours.hummingbirds': 'Tour de Colibríes',
    'tours.hummingbirds.desc': 'Observa más de 20 especies de colibríes en su hábitat natural',
    'tours.oriente': 'Tour del Oriente Antioqueño',
    'tours.oriente.desc': 'Recorre pueblos encantadores: Carmen de Viboral, La Ceja, El Retiro y más',
    'tours.comuna13': 'Comuna 13',
    'tours.comuna13.desc': 'Historia, arte urbano y transformación social en un recorrido inolvidable',
    'tours.cacao': 'Ruta del Cacao',
    'tours.cacao.desc': 'Del grano a la barra: vive la experiencia del chocolate artesanal colombiano',
    'tours.botanical': 'Jardín Botánico & Frutas Tropicales',
    'tours.botanical.desc': 'Explora la biodiversidad y degusta frutas exóticas en un oasis urbano',
    'tours.coffee': 'Ruta del Café',
    'tours.coffee.desc': 'Conoce el proceso del mejor café del mundo desde la finca hasta tu taza',
    'tours.wellness': 'Turismo Wellness',
    'tours.wellness.desc': 'Spa, meditación y conexión con la naturaleza para tu bienestar integral',
    'tours.city': 'City Tour Medellín',
    'tours.city.desc': 'Descubre los íconos de la ciudad de la eterna primavera',
    'tours.paragliding': 'Parapente',
    'tours.paragliding.desc': 'Vuela sobre los valles antioqueños con vistas espectaculares',
    'tours.designers': 'Tour de Diseñadores',
    'tours.designers.desc': 'Recorre los showrooms más exclusivos de la moda colombiana',
    'tours.classic': 'Rodadas Clásicas',
    'tours.classic.desc': 'Pasea en autos clásicos de los años 20s y 30s por las montañas',
    'tours.santafe': 'Santa Fe de Antioquia',
    'tours.santafe.desc': 'Historia colonial y gastronomía tradicional',
    'tours.allies.note': 'Trabajamos en alianza con operadores turísticos certificados',
    'tours.cta': 'Reservar Experiencia',
    
    // Designer Tour Page
    'designers.hero.title': 'Tour de Diseñadores',
    'designers.hero.subtitle': 'Te invitamos a vivir una experiencia única en Medellín',
    'designers.hero.desc': 'Sumérgete en un recorrido que va más allá de lo convencional, donde cada pieza cuenta una historia y cada espacio revela la creatividad de talentos locales. Anímate a descubrir el diseño colombiano de una manera íntima y memorable, en compañía de tu grupo favorito.',
    'designers.intro.title': 'Compras con alma',
    'designers.intro.desc': 'Abrimos las puertas de los showrooms de los diseñadores más destacados. No son simples visitas, sino una exploración profunda sobre la inspiración que da vida a cada pieza.',
    'designers.intro.desc2': 'Este es lugar donde el lujo se fusiona con la autenticidad y el talento local. Queremos que se sientan parte de esta comunidad destacada, donde el diseño se vive y se siente en cada detalle.',
    'designers.intro.cta': '¡Anímate, ven con tu grupo favorito!',
    'designers.logistics.title': 'Tu experiencia, nuestra logística',
    'designers.logistics.desc': 'Un representante de Patryally te recibe directamente en el aeropuerto o en el hotel. Garantizamos una logística impecable de transporte privado, seguro y cómodo.',
    'designers.souvenir.title': 'Souvenir exclusivo',
    'designers.souvenir.desc': 'Incluimos un pequeño souvenir. Dentro de este bolso, te espera un pequeño secreto para hacer tu día aún mejor.',
    'designers.toast.title': 'Brindis de celebración',
    'designers.toast.desc': 'Al final del tour habrá un momento de celebración con un brindis para compartir anécdotas.',
    'designers.includes.title': 'Incluye',
    'designers.includes.guide': 'Guía privado bilingüe',
    'designers.includes.souvenir': 'Souvenir de bienvenida',
    'designers.includes.transport': 'Transporte privado y recogida en el hotel',
    'designers.includes.toast': 'Brindis de despedida',
    'designers.collaborators.title': 'Nuestros Colaboradores',
    'designers.group.title': 'Organízalo como quieras',
    'designers.group.desc': 'Elige la ocasión perfecta para vivir una experiencia de moda única en Medellín.',
    'designers.occasion.friends': 'Plan con amigas',
    'designers.occasion.bachelorette': 'Despedida de soltera',
    'designers.occasion.birthday': 'Celebrar cumpleaños',
    'designers.occasion.custom': 'Tu plan a medida',
    'designers.cta': 'Reservar Tour',
    
    // Pricing Page
    'pricing.hero.title': 'Planes Diseñados Para Ti',
    'pricing.hero.subtitle': 'No solo prestamos un servicio, acompañamos vidas.',
    'pricing.hero.tagline': '',
    
    'pricing.included.title': '¿Qué Incluye?',
    'pricing.included.subtitle': 'Todos nuestros paquetes incluyen servicios premium para garantizar tu comodidad y seguridad',
    
    'pricing.includes.transfers': 'Traslados aeropuerto - hotel - aeropuerto',
    'pricing.includes.breakfast': 'Desayuno incluido',
    'pricing.includes.accommodation': 'Alojamiento según el número de noches elegidas',
    'pricing.includes.sim': 'SIM virtual o física para conectividad de llamadas y datos',
    'pricing.includes.transport': 'Transporte hotel – hospital o clínica + 4 horas adicionales',
    'pricing.includes.companion': 'Acompañamiento permanente por personal de logística y Facilitadora',
    'pricing.includes.language': 'Servicio en idioma español',
    'pricing.includes.insurance': 'Tarjetas de asistencia médica',
    
    'pricing.hotels.title': 'Opciones de Hospedaje',
    'pricing.hotels.perNight': 'Precios por noche (2 personas)',
    'pricing.table.night': 'noche',
    'pricing.calculator.title': 'Calculadora de Precios',
    'pricing.calculator.subtitle': 'Obtén un estimado según tus fechas',
    'pricing.calculator.startDate': 'Fecha de llegada',
    'pricing.calculator.endDate': 'Fecha de salida',
    'pricing.calculator.selectDate': 'Seleccionar fecha',
    'pricing.calculator.hotel': 'Hotel',
    'pricing.calculator.selectHotel': 'Seleccionar hotel',
    'pricing.calculator.persons': 'Personas',
    'pricing.calculator.person': 'persona',
    'pricing.calculator.people': 'personas',
    'pricing.calculator.night': 'noche',
    'pricing.calculator.nights': 'noches',
    'pricing.calculator.estimate': 'Precio aproximado (puede variar según disponibilidad)',
    'pricing.calculator.placeholder': 'Selecciona las fechas y el hotel para ver el precio estimado',
    
    'pricing.table.hotel': 'Hotel',
    'pricing.table.priceCOP': 'Precio COP',
    'pricing.table.priceUSD': 'Precio USD',
    'pricing.table.persons': 'N. de Personas',
    'pricing.table.people': 'personas',
    
    'pricing.insurance.title': 'Tarjetas de Asistencia Médica',
    'pricing.insurance.desc': 'Todos nuestros pacientes internacionales cuentan con tarjetas de asistencia médica, garantizando atención de alta calidad y respaldo durante su estancia.',
    
    'pricing.cta': 'Solicitar Cotización Personalizada',
    
    // Footer
    'footer.plan': 'Planifica tu Viaje',
    'footer.name': 'Nombre',
    'footer.email': 'Correo electrónico',
    'footer.phone': 'Teléfono',
    'footer.message': 'Cuéntanos sobre tu viaje ideal',
    'footer.send': 'Enviar',
    'footer.rights': 'Todos los derechos reservados',
    
    // Testimonials
    'testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    'testimonials.subtitle': 'Historias reales de transformación y confianza',
    'testimonials.1.name': 'María González',
    'testimonials.1.location': 'Miami, Estados Unidos',
    'testimonials.1.text': 'Mi experiencia fue increíble. Desde el primer contacto hasta mi regreso, me sentí acompañada y segura. Los resultados superaron mis expectativas.',
    'testimonials.2.name': 'Carlos Rodríguez',
    'testimonials.2.location': 'Panama City, Panamá',
    'testimonials.2.text': 'El equipo de Patry Ally hizo que todo fuera muy fácil. La logística impecable y los especialistas de primer nivel. Totalmente recomendado.',
    'testimonials.3.name': 'Jennifer Smith',
    'testimonials.3.location': 'Quito, Ecuador',
    'testimonials.3.text': 'La atención bilingüe fue clave para mí. Me sentí como en casa y pude disfrutar de Medellín mientras me recuperaba. Una experiencia única.',

    // Who We Are Section
    'whoweare.label': 'Quiénes Somos',
    'whoweare.title': 'Conoce a tu Aliada',
    'whoweare.founder': 'Fundadora',
    'whoweare.greeting': 'Soy PatryAlly',
    'whoweare.intro': 'Tu aliada en este viaje. Soy una mujer alegre y creativa, que junto a un equipo idóneo, estamos aquí para hacer que tu experiencia en Medellín y sus alrededores sea inolvidable.',
    'whoweare.quality.passionate': 'Apasionada',
    'whoweare.quality.adaptive': 'Adaptable al cambio',
    'whoweare.quality.leader': 'Líder y conciliadora',
    'whoweare.quality.creative': 'Creativa y proactiva',
    'whoweare.origin.title': 'Nace PatryAlly',
    'whoweare.origin.desc': 'PatryAlly nace en 2023 como una agencia especializada en atención VIP, iniciando sus relaciones estratégicas en Panamá y ampliando a otras regiones, gracias a un servicio diferencial de acompañamiento y turismo para eventos sociales de alto nivel y turismo médico especializado.',
    'whoweare.referrals': 'A través de un sistema de referidos, hemos logrado construir una red exclusiva de clientes, desarrollando productos y servicios personalizados hechos a la medida que se adaptan a sus necesidades.',
    'whoweare.services.title': 'Servicios Destacados',
    'whoweare.service1': 'Acompañamiento a pacientes internacionales para tratamientos médicos y odontológicos en Medellín.',
    'whoweare.service2': 'Planificación de eventos sociales y experiencias de turismo diferenciales, como tours exclusivos con diseñadores locales.',
    'whoweare.service3': 'Experiencias innovadoras que apoyan a talentos emergentes y el desarrollo económico del ecosistema turístico regional.',
    'whoweare.mission.title': 'Nuestra Esencia',
    'whoweare.mission.desc': 'PatryAlly acompaña a sus clientes en cada paso del proceso, en la planificación y logística, prestando servicios con los más altos estándares de calidad para mantener la confianza y fidelidad de nuestros clientes, creando una experiencia integral donde cada detalle es cuidado para maximizar su bienestar.',

    // Partners
    'partners.title': 'Algunos de nuestros aliados',
    'partners.subtitle': '',
    'partners.alt': 'Logos de aliados en turismo médico',

    // CTA
    'cta.whatsapp': 'Escríbenos al WhatsApp',
    
    // VIP Form
    'form.title': 'Solicitud de Presupuesto',
    'form.subtitle': 'Completa el formulario y te contactaremos en menos de 24 horas',
    'form.service': 'Servicio de interés',
    'form.details': 'Cuéntanos más sobre lo que necesitas',
    'form.submit': 'Solicitar Presupuesto',
    'form.success.title': '¡Solicitud enviada!',
    'form.success.desc': 'Nuestro equipo VIP te contactará pronto.',

    // Custom Trip Page
    'customTrip.hero.title': 'Viajes Personalizados',
    'customTrip.hero.subtitle': 'Personaliza tu viaje soñado a Colombia con nuestros expertos de Patry Ally',
    'customTrip.title': 'Fácil y rápido. Sigue estos 3 simples pasos y crea tu viaje personalizado',
    'customTrip.step1.desc': 'Completa la información en nuestro formulario y cuéntanos tus intereses y detalles.',
    'customTrip.step2.desc': 'Uno de nuestros expertos en viajes te contactará para diseñar tu viaje perfecto.',
    'customTrip.step3.desc': '¡Confirma tu viaje y prepárate para disfrutar lo mejor de Colombia!',
    'customTrip.desc.title': 'Personaliza tu viaje soñado a Colombia con nuestros expertos en viajes de Patry Ally.',
    'customTrip.desc.p1': 'Los viajes personalizados son itinerarios hechos a medida para viajeros individuales, familias o grupos pequeños. Podemos programar un itinerario según tus intereses, fechas y solicitudes especiales. Nuestros viajes incluyen guías, transporte, entradas y mucho más.',
    'customTrip.desc.p2': 'Completa el formulario a continuación y comencemos a diseñar tu itinerario personalizado.',
    'customTrip.alt.title': '¿No te gustan los formularios?',
    'customTrip.alt.email': 'Escríbenos a',
    'customTrip.alt.suffix': 'con información sobre tus planes de viaje y uno de nuestros especialistas te responderá.',
    
    // Custom Trip Form
    'customTrip.form.travelDate': 'Fecha preferida de viaje',
    'customTrip.form.tripLength': 'Duración preferida del viaje',
    'customTrip.form.tripLengthPlaceholder': 'ej: 7 días',
    'customTrip.form.travelers': 'Total de viajeros en tu grupo',
    'customTrip.form.flexible': 'Mi fecha de salida es flexible',
    'customTrip.form.budget': 'Presupuesto por persona por día',
    'customTrip.form.selectBudget': 'Selecciona tu presupuesto',
    'customTrip.form.accommodation': 'Estilo de alojamiento',
    'customTrip.form.selectAccommodation': 'Selecciona tipo de alojamiento',
    'customTrip.form.individual': 'Alojamiento individual',
    'customTrip.form.double': 'Alojamiento doble',
    'customTrip.form.multiple': 'Alojamiento múltiple',
    'customTrip.form.places': 'Lugares que te gustaría visitar',
    'customTrip.form.interests': 'Tus intereses',
    'customTrip.form.comments': 'Comentarios adicionales',
    'customTrip.form.commentsPlaceholder': 'Cuéntanos más sobre tu viaje ideal...',
    'customTrip.form.travelerInfo': 'Información del Viajero Principal',
    'customTrip.form.fullName': 'Nombre completo',
    'customTrip.form.fullNamePlaceholder': 'Tu nombre completo',
    'customTrip.form.phone': 'Teléfono',
    'customTrip.form.email': 'Correo electrónico',
    'customTrip.form.country': 'País',
    'customTrip.form.countryPlaceholder': 'Tu país de residencia',
    'customTrip.form.howHeard': '¿Cómo te enteraste de Patry Ally?',
    'customTrip.form.selectSource': 'Selecciona una opción',
    'customTrip.form.referral': 'Recomendación',
    'customTrip.form.other': 'Otro',
    'customTrip.form.submit': 'Enviar Solicitud',
    
    // Interests
    'customTrip.interest.gastronomy': 'Gastronomía local',
    'customTrip.interest.city': 'Tours por la ciudad',
    'customTrip.interest.graffiti': 'Tours de graffiti',
    'customTrip.interest.coffee': 'Fincas cafeteras',
    'customTrip.interest.nature': 'Naturaleza - Parques',
    'customTrip.interest.cooking': 'Clases de cocina',
    'customTrip.interest.urban': 'Experiencias urbanas',
    'customTrip.interest.communities': 'Comunidades locales',
    'customTrip.interest.culture': 'Cultura del café',

    // Custom Trip Services
    'customTrip.services.title': 'Nuestros Servicios',
    'customTrip.services.transport.title': 'Transporte Privado',
    'customTrip.services.transport.desc': 'Vehículos privados de alta gama con conductor bilingüe para todos tus traslados. Desde la recogida en el aeropuerto hasta cada destino de tu itinerario, viaja con total comodidad y seguridad.',
    'customTrip.services.transport.b1': 'Recogida y traslado aeropuerto',
    'customTrip.services.transport.b2': 'Conductor bilingüe profesional',
    'customTrip.services.transport.b3': 'Vehículos modernos y seguros',
    'customTrip.services.transport.b4': 'Disponibilidad 24/7',
    'customTrip.services.spa.title': 'Spa & Bienestar',
    'customTrip.services.spa.desc': 'Accede a los mejores spas y centros de bienestar de Medellín. Tratamientos personalizados, masajes relajantes y experiencias de rejuvenecimiento para complementar tu viaje.',
    'customTrip.services.spa.b1': 'Masajes y tratamientos premium',
    'customTrip.services.spa.b2': 'Centros de bienestar exclusivos',
    'customTrip.services.spa.b3': 'Terapias personalizadas',
    'customTrip.services.spa.b4': 'Experiencias de relajación total',
    'customTrip.services.hotels.title': 'Hoteles Seleccionados',
    'customTrip.services.hotels.desc': 'Alojamiento en hoteles cuidadosamente seleccionados que combinan confort, ubicación estratégica y la mejor hospitalidad colombiana. Desde boutique hasta cadenas reconocidas.',
    'customTrip.services.hotels.b1': 'Ubicaciones estratégicas en la ciudad',
    'customTrip.services.hotels.b2': 'Hoteles boutique y de cadena',
    'customTrip.services.hotels.b3': 'Desayuno incluido',
    'customTrip.services.hotels.b4': 'Soporte y logística completa',
    'customTrip.collaborators.title': 'Nuestros Colaboradores',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.health': 'Health',
    'nav.dental': 'Dental',
    'nav.medicine': 'Medicine',
    'nav.tours': 'Experience Tour',
    'nav.customTrips': 'Logistics Experience',
    'nav.logistics': 'Designer Tour',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.cta': 'Request Evaluation',
    
    // Hero
    'hero.slide1.title': 'Medical Excellence with Local Heart',
    'hero.slide1.subtitle': 'Your ideal ally in VIP medical planning in Medellín',
    'hero.slide1.cta': 'Start Process',
    'hero.slide2.title': 'Comprehensive Specialized Dentistry',
    'hero.slide2.subtitle': 'We have the best specialists in cosmetic dentistry, oral rehabilitation, implants, and much more.',
    'hero.slide2.cta': 'See more',
    'hero.slide3.title': 'Colombia at Its Finest',
    'hero.slide3.subtitle': 'Bilingual logistics and exclusive experiences while you recover',
    'hero.slide3.cta': 'Explore Experiences',
    
    // About Section
    'about.label': 'About Us',
    'about.title': "We don't just provide a service: we accompany lives",
    'about.description': 'Patry Ally was born from a passion to transform medical tourism into a warm, human experience. We are the bridge between international patients and the best specialists in Colombia, guaranteeing peace of mind, safety, and exceptional results.',
    'about.stat1': 'Patients',
    'about.stat2': 'Specialists',
    'about.stat3': 'Satisfaction',
    'about.human.title': 'Human Accompaniment',
    'about.human.desc': "We're with you every step, from arrival to return. You're not a number, you're part of our family.",
    'about.network.title': 'Specialist Network',
    'about.network.desc': 'Access to internationally certified surgeons and specialists with years of experience.',
    'about.quality.title': 'Guaranteed Quality',
    'about.quality.desc': 'Partnerships with high-level clinics and comprehensive post-operative follow-up.',

    // Specialties
    'specialties.label': 'Specialties',
    'specialties.title': 'Our Areas of Excellence',
    'specialties.subtitle': 'Access the best specialists in Colombia with cutting-edge technology',
    'specialties.plastic': 'Plastic Surgery',
    'specialties.plastic.desc': 'Aesthetic and reconstructive procedures with internationally renowned surgeons.',
    'specialties.dental': 'Dentistry',
    'specialties.dental.desc': 'Smile design, implants, and oral rehabilitation with state-of-the-art technology.',
    'specialties.cardio': 'Cardiology',
    'specialties.cardio.desc': 'Comprehensive diagnosis and treatment of cardiovascular diseases.',
    'specialties.gastro': 'Gastroenterology',
    'specialties.gastro.desc': 'Complete evaluation of the digestive system with high-tech equipment.',
    'specialties.checkups': 'Executive Checkups',
    'specialties.checkups.desc': 'Comprehensive health evaluation for executives and professionals.',
    'specialties.sports': 'Sports Medicine',
    'specialties.sports.desc': 'Treatment and prevention of sports injuries with certified specialists.',
    'specialties.cta': 'Learn more',

    // Process Timeline
    'process.label': 'Your Process',
    'process.title': '360° Accompaniment',
    'process.subtitle': 'We guide you every step of the way towards your transformation',
    'process.step1.title': 'Virtual Consultation',
    'process.step1.desc': 'We evaluate your case and design a personalized plan with the best specialists.',
    'process.step2.title': 'VIP Arrival',
    'process.step2.desc': 'Airport pickup, bilingual transport, and first-class accommodation.',
    'process.step3.title': 'Medical Procedure',
    'process.step3.desc': 'Excellent medical care with constant monitoring from our team.',
    'process.step4.title': 'Recovery & Wellness',
    'process.step4.desc': 'Post-operative care, spa, and unique experiences while you recover.',
    
    // Essence Section
    'essence.title': 'Accompaniment is our Essence',
    'essence.subtitle': 'We are your ally in every step of the medical process, guaranteeing peace of mind and safety from first contact to your return home.',
    'essence.cta': 'Learn our method',
    
    // Pillars Section
    'pillars.title': 'Pillars of Excellence',
    'pillars.medical.title': 'Medical Excellence',
    'pillars.medical.desc': 'High-level specialists with international certifications and years of experience.',
    'pillars.logistics.title': 'VIP Logistics',
    'pillars.logistics.desc': 'Door-to-door bilingual transport and complete stay management.',
    'pillars.experiences.title': 'Unique Experiences',
    'pillars.experiences.desc': 'Exclusive tours designed for you to discover the best of Medellín.',
    
    // CTA Banner
    'cta.banner.title': 'Ready for your new version?',
    'cta.banner.subtitle': 'Talk to a VIP advisor',
    'cta.banner.button': 'Direct WhatsApp',
    
    // Difference Section
    'difference.title': 'The Patry Ally Difference',
    'difference.subtitle': 'We transform medical tourism into a human and personalized experience',
    'difference.human.title': 'Human Accompaniment',
    'difference.human.desc': "We're with you every step, from arrival to return. You're not a number, you're part of our family.",
    'difference.security.title': 'Security & Trust',
    'difference.security.desc': 'Comprehensive insurance management and partnerships with internationally certified high-level clinics.',
    'difference.logistics.title': 'Door-to-Door Logistics',
    'difference.logistics.desc': 'Guaranteed punctuality at airports, medical appointments, and transfers. Your time is invaluable.',
    
    // Services Grid
    'services.title': 'Our Services',
    'services.subtitle': 'Experiences designed for your wellbeing',
    'services.medicine': 'Specialized Medicine',
    'services.medicine.desc': 'Plastic surgery, dentistry and more',
    'services.tours': 'Premium Experiences',
    'services.tours.desc': 'Exclusive tours in Medellín',
    'services.logistics': 'VIP Logistics',
    'services.logistics.desc': 'Luxury transport and accommodation',
    
    // Medicine Page (Legacy)
    'medicine.hero.title': 'Health & Dental',
    'medicine.hero.subtitle': 'Access the best specialists in Colombia with personalized care',
    'medicine.specialties.title': 'Our Specialties',
    'medicine.plastic': 'Plastic Surgery',
    'medicine.plastic.desc': 'Aesthetic procedures with internationally renowned certified surgeons',
    'medicine.dental': 'Smile Design',
    'medicine.dental.desc': 'Cutting-edge aesthetic dentistry with state-of-the-art technology',
    'medicine.gastro': 'Gastroenterology',
    'medicine.gastro.desc': 'Comprehensive diagnosis and treatment of the digestive system',
    'medicine.cardio': 'Executive Checkups',
    'medicine.cardio.desc': 'Complete health evaluation with high-tech equipment',
    'medicine.implants': 'Dental Implants',
    'medicine.implants.desc': 'Permanent solutions for your perfect smile',
    'medicine.tech.title': 'Technology & Diagnostics',
    'medicine.tech.subtitle': 'State-of-the-art equipment for your peace of mind',
    'medicine.ultrasound': 'Ultrasounds',
    'medicine.labs': 'Laboratories',
    'medicine.sports': 'Sports Medicine',
    'medicine.cta': 'Request evaluation',

    // Health Page (New Authority Structure)
    'health.hero.label': 'Elite Medical Tourism',
    'health.hero.title': 'Medical Excellence in Medellín',
    'health.hero.subtitle': 'Access world-class specialists, cutting-edge technology, and comprehensive support that guarantees your peace of mind every step of the way.',
    'health.hero.cta': 'Request Virtual Evaluation',

    'health.banner.text': 'Our value is not just medicine, it\'s bilingual accompaniment at every appointment and comprehensive management of your procedures.',

    'health.directory.label': 'High-Level Directory',
    'health.directory.title': 'Our Medical Team',
    'health.directory.subtitle': 'Internationally certified specialists with years of experience treating international patients',

    'health.plastic.title': 'Plastic & Reconstructive Surgery',
    'health.plastic.desc': 'Internationally renowned surgeons specialized in aesthetic and reconstructive procedures with the most advanced techniques.',
    'health.plastic.proc1': 'HD Liposuction & Fat Transfer',
    'health.plastic.proc2': 'Breast Augmentation & Reduction',
    'health.plastic.proc3': 'Rhinoplasty & Facial Surgery',
    'health.plastic.proc4': 'Tummy Tuck & Body Contouring',

    'health.gastro.title': 'Gastroenterology',
    'health.gastro.desc': 'Comprehensive diagnosis and treatment of the digestive system with state-of-the-art endoscopic technology.',
    'health.gastro.proc1': 'Intragastric Balloon',
    'health.gastro.proc2': 'Digestive Endoscopy',
    'health.gastro.proc3': 'High-Definition Colonoscopy',

    'health.cardio.title': 'Cardiology',
    'health.cardio.desc': 'Complete cardiovascular evaluation with high-tech equipment and certified specialists.',
    'health.cardio.proc1': 'Doppler Echocardiogram',
    'health.cardio.proc2': 'Stress Test',
    'health.cardio.proc3': '24h Holter Monitoring',

    'health.neuro.title': 'Neurophysiology',
    'health.neuro.desc': 'Advanced neurological diagnosis for evaluation of the central and peripheral nervous system.',
    'health.neuro.proc1': 'Electroencephalogram (EEG)',
    'health.neuro.proc2': 'Electromyography',
    'health.neuro.proc3': 'Evoked Potentials',

    'health.ortho.title': 'Orthopedics',
    'health.ortho.desc': 'Treatment of musculoskeletal injuries with surgeons specialized in sports medicine.',
    'health.ortho.proc1': 'Knee Arthroscopy',
    'health.ortho.proc2': 'Joint Replacement',
    'health.ortho.proc3': 'Minimally Invasive Spine Surgery',

    'health.dental.title': 'High-Level Dentistry',
    'health.dental.desc': 'Comprehensive smile design with CAD/CAM technology and aesthetic dental specialists.',
    'health.dental.proc1': 'Digital Smile Design',
    'health.dental.proc2': 'Premium Dental Implants',
    'health.dental.proc3': 'Porcelain Veneers',
    'health.dental.proc4': 'Full Oral Rehabilitation',

    'health.cta.consult': 'Consult Specialist',

    'health.alliances.label': 'Institutional Network',
    'health.alliances.title': 'Strategic Alliances',
    'health.alliances.subtitle': 'Backed by the most prestigious medical tourism institutions in Colombia',
    'health.alliances.partners': 'We work with the best clinics and laboratories in Medellín',

    'health.alliance.cluster': 'Cluster Medellín Health City',
    'health.alliance.cluster.desc': 'Active members of the most important health tourism ecosystem in Latin America.',
    'health.alliance.clinics': 'Certified Clinics',
    'health.alliance.clinics.desc': 'Network of clinics with JCI certifications and international accreditations.',

    'health.exec.label': 'Premium Diagnostics',
    'health.exec.title': 'Executive Checkup',
    'health.exec.description': 'Comprehensive health evaluation designed for international executives and professionals. Complete diagnosis in record time with the best specialists.',
    'health.exec.cta': 'Schedule Executive Checkup',

    'health.exec.echo': 'Ultrasounds',
    'health.exec.echo.desc': 'Abdominal, pelvic, thyroid and vascular ultrasound with state-of-the-art equipment.',
    'health.exec.ecg': 'Electrocardiogram',
    'health.exec.ecg.desc': 'Evaluation of cardiac electrical activity for early detection.',
    'health.exec.holter': '24-Hour Holter',
    'health.exec.holter.desc': 'Continuous monitoring of heart rhythm during daily activities.',
    'health.exec.lab': 'Pathology Laboratory',
    'health.exec.lab.desc': 'Complete clinical analysis with results in 24-48 hours.',
    'health.exec.molecular': 'Molecular Diagnostics',
    'health.exec.molecular.desc': 'Genetic testing and high-precision tumor markers.',
    'health.exec.sports': 'BIUMAN Sports Medicine',
    'health.exec.sports.desc': 'Functional evaluation and injury prevention for athletes.',

    'health.exec.biuman.title': 'BIUMAN Sports Medicine',
    'health.exec.biuman.desc': 'Specialized program in biomechanical evaluation, injury prevention, and sports performance optimization with motion analysis technology.',

    'health.routes.title': 'Fast Diagnostic Routes',
    'health.routes.desc': 'We design efficient diagnostic routes for international executives who need complete results in limited time.',
    'health.routes.item1': 'Complete cardiovascular checkup in 4 hours',
    'health.routes.item2': 'Preventive oncological profile in 24 hours',
    'health.routes.item3': 'Comprehensive health evaluation in 48 hours',
    'health.routes.time': 'Complete results',
    'health.allies.title': 'Allies',


    
    // Tours Page
    'tours.hero.title': 'Experiences & Tours',
    'tours.hero.subtitle': 'Discover Colombia with exclusive experiences designed for you',
    'tours.orchids': 'Alma del Bosque Orchids',
    'tours.orchids.desc': 'Immerse yourself in the world of orchids at a unique natural sanctuary',
    'tours.hummingbirds': 'Hummingbird Tour',
    'tours.hummingbirds.desc': 'Observe over 20 species of hummingbirds in their natural habitat',
    'tours.oriente': 'Eastern Antioquia Tour',
    'tours.oriente.desc': 'Explore charming villages: Carmen de Viboral, La Ceja, El Retiro and more',
    'tours.comuna13': 'Comuna 13',
    'tours.comuna13.desc': 'History, street art and social transformation in an unforgettable tour',
    'tours.cacao': 'Cacao Route',
    'tours.cacao.desc': 'From bean to bar: experience artisanal Colombian chocolate',
    'tours.botanical': 'Botanical Garden & Tropical Fruits',
    'tours.botanical.desc': 'Explore biodiversity and taste exotic fruits in an urban oasis',
    'tours.coffee': 'Coffee Route',
    'tours.coffee.desc': 'Discover the process of the world\'s best coffee from farm to cup',
    'tours.wellness': 'Wellness Tourism',
    'tours.wellness.desc': 'Spa, meditation and nature connection for your integral wellbeing',
    'tours.city': 'Medellín City Tour',
    'tours.city.desc': 'Discover the icons of the city of eternal spring',
    'tours.paragliding': 'Paragliding',
    'tours.paragliding.desc': 'Fly over the Antioquia valleys with spectacular views',
    'tours.designers': 'Designer Tour',
    'tours.designers.desc': 'Visit the most exclusive showrooms of Colombian fashion',
    'tours.classic': 'Classic Car Rides',
    'tours.classic.desc': 'Ride in classic cars from the 20s and 30s through the mountains',
    'tours.santafe': 'Santa Fe de Antioquia',
    'tours.santafe.desc': 'Colonial history and traditional gastronomy',
    'tours.allies.note': 'We work in partnership with certified tour operators',
    'tours.cta': 'Book Experience',
    
    // Designer Tour Page
    'designers.hero.title': 'Designer Tour',
    'designers.hero.subtitle': 'We invite you to live a unique experience in Medellín',
    'designers.hero.desc': 'Dive into a journey that goes beyond the conventional, where every piece tells a story and every space reveals the creativity of local talents. Dare to discover Colombian design in an intimate and memorable way, with your favorite group.',
    'designers.intro.title': 'Shopping with soul',
    'designers.intro.desc': 'We open the doors of the most renowned designers\' showrooms. These are not simple visits, but a deep exploration of the inspiration that brings each piece to life.',
    'designers.intro.desc2': 'This is a place where luxury merges with authenticity and local talent. We want you to feel part of this outstanding community, where design is lived and felt in every detail.',
    'designers.intro.cta': 'Come with your favorite group!',
    'designers.logistics.title': 'Your experience, our logistics',
    'designers.logistics.desc': 'A Patryally representative picks you up directly at the airport or hotel. We guarantee impeccable logistics with private, safe and comfortable transport.',
    'designers.souvenir.title': 'Exclusive souvenir',
    'designers.souvenir.desc': 'We include a small souvenir. Inside this bag, a little secret awaits to make your day even better.',
    'designers.toast.title': 'Celebration toast',
    'designers.toast.desc': 'At the end of the tour there will be a moment of celebration with a toast to share stories.',
    'designers.includes.title': 'Includes',
    'designers.includes.guide': 'Private bilingual guide',
    'designers.includes.souvenir': 'Welcome souvenir',
    'designers.includes.transport': 'Private transport and hotel pickup',
    'designers.includes.toast': 'Farewell toast',
    'designers.collaborators.title': 'Our Collaborators',
    'designers.group.title': 'Organize it your way',
    'designers.group.desc': 'Choose the perfect occasion to live a unique fashion experience in Medellín.',
    'designers.occasion.friends': 'Girls\' plan',
    'designers.occasion.bachelorette': 'Bachelorette party',
    'designers.occasion.birthday': 'Birthday celebration',
    'designers.occasion.custom': 'Your custom plan',
    'designers.cta': 'Book Tour',
    
    // Pricing Page
    'pricing.hero.title': 'Plans Designed For You',
    'pricing.hero.subtitle': 'We don\'t just provide a service, we accompany lives.',
    'pricing.hero.tagline': '',
    
    'pricing.included.title': 'What\'s Included?',
    'pricing.included.subtitle': 'All our packages include premium services to guarantee your comfort and safety',
    
    'pricing.includes.transfers': 'Airport - hotel - airport transfers',
    'pricing.includes.breakfast': 'Breakfast included',
    'pricing.includes.accommodation': 'Accommodation according to the number of nights chosen',
    'pricing.includes.sim': 'Virtual or physical SIM for call and data connectivity',
    'pricing.includes.transport': 'Hotel - hospital or clinic transport + 4 additional hours',
    'pricing.includes.companion': 'Permanent accompaniment by logistics staff and Facilitator',
    'pricing.includes.language': 'Service in Spanish',
    'pricing.includes.insurance': 'Medical assistance cards',
    
    'pricing.hotels.title': 'Accommodation Options',
    'pricing.hotels.perNight': 'Prices per night (2 people)',
    'pricing.table.night': 'night',
    'pricing.calculator.title': 'Price Calculator',
    'pricing.calculator.subtitle': 'Get an estimate based on your dates',
    'pricing.calculator.startDate': 'Arrival date',
    'pricing.calculator.endDate': 'Departure date',
    'pricing.calculator.selectDate': 'Select date',
    'pricing.calculator.hotel': 'Hotel',
    'pricing.calculator.selectHotel': 'Select hotel',
    'pricing.calculator.persons': 'Guests',
    'pricing.calculator.person': 'person',
    'pricing.calculator.people': 'people',
    'pricing.calculator.night': 'night',
    'pricing.calculator.nights': 'nights',
    'pricing.calculator.estimate': 'Approximate price (may vary based on availability)',
    'pricing.calculator.placeholder': 'Select dates and hotel to see estimated price',
    
    'pricing.table.hotel': 'Hotel',
    'pricing.table.priceCOP': 'Price COP',
    'pricing.table.priceUSD': 'Price USD',
    'pricing.table.persons': 'No. of People',
    'pricing.table.people': 'people',
    
    'pricing.insurance.title': 'Medical Assistance Cards',
    'pricing.insurance.desc': 'All our international patients have medical assistance cards, guaranteeing high-quality care and support during their stay.',
    
    'pricing.cta': 'Request Personalized Quote',
    
    // Footer
    'footer.plan': 'Plan Your Trip',
    'footer.name': 'Name',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.message': 'Tell us about your ideal trip',
    'footer.send': 'Send',
    'footer.rights': 'All rights reserved',
    
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Real stories of transformation and trust',
    'testimonials.1.name': 'María González',
    'testimonials.1.location': 'Miami, United States',
    'testimonials.1.text': 'My experience was incredible. From first contact to my return, I felt accompanied and safe. The results exceeded my expectations.',
    'testimonials.2.name': 'Carlos Rodríguez',
    'testimonials.2.location': 'Panama City, Panamá',
    'testimonials.2.text': 'The Patry Ally team made everything so easy. Impeccable logistics and top-level specialists. Totally recommended.',
    'testimonials.3.name': 'Jennifer Smith',
    'testimonials.3.location': 'Quito, Ecuador',
    'testimonials.3.text': 'The bilingual care was key for me. I felt at home and could enjoy Medellín while recovering. A unique experience.',

    // Who We Are Section
    'whoweare.label': 'Who We Are',
    'whoweare.title': 'Meet Your Ally',
    'whoweare.founder': 'Founder',
    'whoweare.greeting': "I'm Patry",
    'whoweare.intro': 'Your ally on this journey. I am a cheerful and creative woman who, together with a skilled team, is here to make your experience in Medellín and its surroundings unforgettable.',
    'whoweare.quality.passionate': 'Passionate',
    'whoweare.quality.adaptive': 'Adaptable to change',
    'whoweare.quality.leader': 'Leader & mediator',
    'whoweare.quality.creative': 'Creative & proactive',
    'whoweare.origin.title': 'PatryAlly is Born',
    'whoweare.origin.desc': 'PatryAlly was born in 2023 as an agency specialized in VIP care, starting strategic relationships in Panama and expanding to other regions, thanks to a differential service of accompaniment and tourism for high-level social events and specialized medical tourism.',
    'whoweare.referrals': 'Through a referral system, we have built an exclusive network of clients, developing personalized products and services tailored to their needs.',
    'whoweare.services.title': 'Featured Services',
    'whoweare.service1': 'Accompaniment for international patients for medical and dental treatments in Medellín.',
    'whoweare.service2': 'Planning social events and differential tourism experiences, such as exclusive tours with local designers.',
    'whoweare.service3': 'Innovative experiences that support emerging talents and the economic development of the regional tourism ecosystem.',
    'whoweare.mission.title': 'Our Essence',
    'whoweare.mission.desc': 'PatryAlly accompanies its clients every step of the way, in planning and logistics, providing services with the highest quality standards to maintain the trust and loyalty of our clients, creating a comprehensive experience where every detail is cared for to maximize their wellbeing.',

    // Partners
    'partners.title': 'Some of our partners',
    'partners.subtitle': '',
    'partners.alt': 'Medical tourism partner logos',

    // CTA
    'cta.whatsapp': 'Message us on WhatsApp',
    
    // VIP Form
    'form.title': 'Budget Request',
    'form.subtitle': 'Fill out the form and we will contact you within 24 hours',
    'form.service': 'Service of interest',
    'form.details': 'Tell us more about what you need',
    'form.submit': 'Request Quote',
    'form.success.title': 'Request sent!',
    'form.success.desc': 'Our VIP team will contact you soon.',

    // Custom Trip Page
    'customTrip.hero.title': 'Custom Trips',
    'customTrip.hero.subtitle': 'Customize your unique, dream Colombian trip with our travel experts at Patry Ally',
    'customTrip.title': 'Easy and smart. Follow these 3 simple steps and create your customized trip',
    'customTrip.step1.desc': 'Fill out the information on our form and let us know your interests and details.',
    'customTrip.step2.desc': 'One of our travel experts will contact you to design your perfect trip.',
    'customTrip.step3.desc': 'Confirm your trip and be prepared to enjoy the best of Colombia!',
    'customTrip.desc.title': 'Customize your dream Colombian trip with our knowledgeable travel experts at Patry Ally.',
    'customTrip.desc.p1': 'Custom trips are tailor-made itineraries designed for individual travelers, families, or small groups. We can schedule an itinerary around your interests, dates, and special requests. Our trips include guides, transport, entrance fees, and much more.',
    'customTrip.desc.p2': 'Fill out the form below and let\'s get started designing your customized itinerary.',
    'customTrip.alt.title': 'Not a fan of contact forms?',
    'customTrip.alt.email': 'Email us at',
    'customTrip.alt.suffix': 'with information on your desired travel plans and one of our travel specialists will get back to you.',
    
    // Custom Trip Form
    'customTrip.form.travelDate': 'Preferred travel date',
    'customTrip.form.tripLength': 'Preferred length of trip',
    'customTrip.form.tripLengthPlaceholder': 'e.g: 7 days',
    'customTrip.form.travelers': 'Total travelers in your group',
    'customTrip.form.flexible': 'My departure date is flexible',
    'customTrip.form.budget': 'Budget per person per day',
    'customTrip.form.selectBudget': 'Select your budget',
    'customTrip.form.accommodation': 'Accommodation style',
    'customTrip.form.selectAccommodation': 'Select accommodation type',
    'customTrip.form.individual': 'Individual accommodation',
    'customTrip.form.double': 'Double accommodation',
    'customTrip.form.multiple': 'Multiple accommodation',
    'customTrip.form.places': 'Places you\'d like to visit',
    'customTrip.form.interests': 'Your interests',
    'customTrip.form.comments': 'Additional Comments',
    'customTrip.form.commentsPlaceholder': 'Tell us more about your ideal trip...',
    'customTrip.form.travelerInfo': 'Primary Traveler Information',
    'customTrip.form.fullName': 'Full name',
    'customTrip.form.fullNamePlaceholder': 'Your full name',
    'customTrip.form.phone': 'Phone',
    'customTrip.form.email': 'Email',
    'customTrip.form.country': 'Country',
    'customTrip.form.countryPlaceholder': 'Your country of residence',
    'customTrip.form.howHeard': 'How did you hear about Patry Ally?',
    'customTrip.form.selectSource': 'Select an option',
    'customTrip.form.referral': 'Referral',
    'customTrip.form.other': 'Other',
    'customTrip.form.submit': 'Submit Request',
    
    // Interests
    'customTrip.interest.gastronomy': 'Local gastronomy',
    'customTrip.interest.city': 'City sightseeing tours',
    'customTrip.interest.graffiti': 'Graffiti tours',
    'customTrip.interest.coffee': 'Coffee farms',
    'customTrip.interest.nature': 'Nature - National Parks',
    'customTrip.interest.cooking': 'Cooking classes',
    'customTrip.interest.urban': 'Urban experiences',
    'customTrip.interest.communities': 'Local communities',
    'customTrip.interest.culture': 'Colombian coffee culture',

    // Custom Trip Services
    'customTrip.services.title': 'Our Services',
    'customTrip.services.transport.title': 'Private Transportation',
    'customTrip.services.transport.desc': 'Premium private vehicles with bilingual drivers for all your transfers. From airport pickup to every destination on your itinerary, travel in complete comfort and safety.',
    'customTrip.services.transport.b1': 'Airport pickup and transfer',
    'customTrip.services.transport.b2': 'Professional bilingual driver',
    'customTrip.services.transport.b3': 'Modern and safe vehicles',
    'customTrip.services.transport.b4': '24/7 availability',
    'customTrip.services.spa.title': 'Spa & Wellness',
    'customTrip.services.spa.desc': 'Access the best spas and wellness centers in Medellín. Personalized treatments, relaxing massages, and rejuvenation experiences to complement your trip.',
    'customTrip.services.spa.b1': 'Premium massages and treatments',
    'customTrip.services.spa.b2': 'Exclusive wellness centers',
    'customTrip.services.spa.b3': 'Personalized therapies',
    'customTrip.services.spa.b4': 'Total relaxation experiences',
    'customTrip.services.hotels.title': 'Selected Hotels',
    'customTrip.services.hotels.desc': 'Accommodation in carefully selected hotels that combine comfort, strategic location, and the best Colombian hospitality. From boutique to recognized chains.',
    'customTrip.services.hotels.b1': 'Strategic city locations',
    'customTrip.services.hotels.b2': 'Boutique and chain hotels',
    'customTrip.services.hotels.b3': 'Breakfast included',
    'customTrip.services.hotels.b4': 'Full support and logistics',
    'customTrip.collaborators.title': 'Our Collaborators',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
